# Stage 1: Build
FROM golang:1.26.4 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -o sam-router ./cmd/sam-router

# Stage 2: Final
FROM gcr.io/distroless/static:latest
COPY --from=builder /app/sam-router /
ENTRYPOINT ["/sam-router"]
