# Stage 1: Build
FROM golang:1.27 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -o sam-box ./cmd/sam-box

# Stage 2: Final
FROM gcr.io/distroless/static:nonroot
COPY --from=builder --chown=nonroot:nonroot /app/sam-box /
USER nonroot:nonroot
ENTRYPOINT ["/sam-box"]
