apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam-mesh.fullname" . }}-secrets
  labels:
    {{- include "sam-mesh.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.controlPlane.adminToken | b64enc | quote }}
  db-password: {{ .Values.database.postgres.password | b64enc | quote }}
