// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/sam.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	ServiceType_SERVICE_TYPE_MCP         ServiceType = 1
	ServiceType_SERVICE_TYPE_INFERENCE   ServiceType = 2
	ServiceType_SERVICE_TYPE_A2A         ServiceType = 3
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_MCP",
		2: "SERVICE_TYPE_INFERENCE",
		3: "SERVICE_TYPE_A2A",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE_TYPE_MCP":         1,
		"SERVICE_TYPE_INFERENCE":   2,
		"SERVICE_TYPE_A2A":         3,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sam_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_api_sam_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{0}
}

type MeshEvent_Type int32

const (
	MeshEvent_BANNED       MeshEvent_Type = 0
	MeshEvent_KEY_ROTATION MeshEvent_Type = 1
)

// Enum value maps for MeshEvent_Type.
var (
	MeshEvent_Type_name = map[int32]string{
		0: "BANNED",
		1: "KEY_ROTATION",
	}
	MeshEvent_Type_value = map[string]int32{
		"BANNED":       0,
		"KEY_ROTATION": 1,
	}
)

func (x MeshEvent_Type) Enum() *MeshEvent_Type {
	p := new(MeshEvent_Type)
	*p = x
	return p
}

func (x MeshEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeshEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sam_proto_enumTypes[1].Descriptor()
}

func (MeshEvent_Type) Type() protoreflect.EnumType {
	return &file_api_sam_proto_enumTypes[1]
}

func (x MeshEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeshEvent_Type.Descriptor instead.
func (MeshEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{2, 0}
}

type AuthFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biscuit       []byte                 `protobuf:"bytes,1,opt,name=biscuit,proto3" json:"biscuit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthFrame) Reset() {
	*x = AuthFrame{}
	mi := &file_api_sam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFrame) ProtoMessage() {}

func (x *AuthFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFrame.ProtoReflect.Descriptor instead.
func (*AuthFrame) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{0}
}

func (x *AuthFrame) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // populated only if success is false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_sam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MeshEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MeshEvent_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=sam.v1.MeshEvent_Type" json:"type,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NewPublicKey  []byte                 `protobuf:"bytes,4,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshEvent) Reset() {
	*x = MeshEvent{}
	mi := &file_api_sam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshEvent) ProtoMessage() {}

func (x *MeshEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshEvent.ProtoReflect.Descriptor instead.
func (*MeshEvent) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{2}
}

func (x *MeshEvent) GetType() MeshEvent_Type {
	if x != nil {
		return x.Type
	}
	return MeshEvent_BANNED
}

func (x *MeshEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *MeshEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MeshEvent) GetNewPublicKey() []byte {
	if x != nil {
		return x.NewPublicKey
	}
	return nil
}

func (x *MeshEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_sam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *EnrollRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BiscuitToken  []byte                 `protobuf:"bytes,1,opt,name=biscuit_token,json=biscuitToken,proto3" json:"biscuit_token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	HubPublicKey  []byte                 `protobuf:"bytes,3,opt,name=hub_public_key,json=hubPublicKey,proto3" json:"hub_public_key,omitempty"`
	HubAddresses  []string               `protobuf:"bytes,4,rep,name=hub_addresses,json=hubAddresses,proto3" json:"hub_addresses,omitempty"`
	Expiration    int64                  `protobuf:"varint,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_sam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollResponse) GetBiscuitToken() []byte {
	if x != nil {
		return x.BiscuitToken
	}
	return nil
}

func (x *EnrollResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EnrollResponse) GetHubPublicKey() []byte {
	if x != nil {
		return x.HubPublicKey
	}
	return nil
}

func (x *EnrollResponse) GetHubAddresses() []string {
	if x != nil {
		return x.HubAddresses
	}
	return nil
}

func (x *EnrollResponse) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServiceType            `protobuf:"varint,1,opt,name=type,proto3,enum=sam.v1.ServiceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_api_sam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceInfo) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CommandBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandBackend) Reset() {
	*x = CommandBackend{}
	mi := &file_api_sam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandBackend) ProtoMessage() {}

func (x *CommandBackend) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandBackend.ProtoReflect.Descriptor instead.
func (*CommandBackend) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{6}
}

func (x *CommandBackend) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandBackend) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type RegisterServiceRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Types that are valid to be assigned to Backend:
	//
	//	*RegisterServiceRequest_TargetUrl
	//	*RegisterServiceRequest_Command
	Backend       isRegisterServiceRequest_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_api_sam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterServiceRequest) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *RegisterServiceRequest) GetBackend() isRegisterServiceRequest_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *RegisterServiceRequest) GetTargetUrl() string {
	if x != nil {
		if x, ok := x.Backend.(*RegisterServiceRequest_TargetUrl); ok {
			return x.TargetUrl
		}
	}
	return ""
}

func (x *RegisterServiceRequest) GetCommand() *CommandBackend {
	if x != nil {
		if x, ok := x.Backend.(*RegisterServiceRequest_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isRegisterServiceRequest_Backend interface {
	isRegisterServiceRequest_Backend()
}

type RegisterServiceRequest_TargetUrl struct {
	TargetUrl string `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3,oneof"`
}

type RegisterServiceRequest_Command struct {
	Command *CommandBackend `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

func (*RegisterServiceRequest_TargetUrl) isRegisterServiceRequest_Backend() {}

func (*RegisterServiceRequest_Command) isRegisterServiceRequest_Backend() {}

type DiscoveredProvider struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LocalProxyUrl  string                 `protobuf:"bytes,2,opt,name=local_proxy_url,json=localProxyUrl,proto3" json:"local_proxy_url,omitempty"`
	SrvName        string                 `protobuf:"bytes,3,opt,name=srv_name,json=srvName,proto3" json:"srv_name,omitempty"`
	SrvDescription string                 `protobuf:"bytes,4,opt,name=srv_description,json=srvDescription,proto3" json:"srv_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiscoveredProvider) Reset() {
	*x = DiscoveredProvider{}
	mi := &file_api_sam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredProvider) ProtoMessage() {}

func (x *DiscoveredProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredProvider.ProtoReflect.Descriptor instead.
func (*DiscoveredProvider) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoveredProvider) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DiscoveredProvider) GetLocalProxyUrl() string {
	if x != nil {
		return x.LocalProxyUrl
	}
	return ""
}

func (x *DiscoveredProvider) GetSrvName() string {
	if x != nil {
		return x.SrvName
	}
	return ""
}

func (x *DiscoveredProvider) GetSrvDescription() string {
	if x != nil {
		return x.SrvDescription
	}
	return ""
}

type HubInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OidcIssuer    string                 `protobuf:"bytes,1,opt,name=oidc_issuer,json=oidcIssuer,proto3" json:"oidc_issuer,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Audience      string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubInfoResponse) Reset() {
	*x = HubInfoResponse{}
	mi := &file_api_sam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubInfoResponse) ProtoMessage() {}

func (x *HubInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubInfoResponse.ProtoReflect.Descriptor instead.
func (*HubInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{9}
}

func (x *HubInfoResponse) GetOidcIssuer() string {
	if x != nil {
		return x.OidcIssuer
	}
	return ""
}

func (x *HubInfoResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HubInfoResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

var File_api_sam_proto protoreflect.FileDescriptor

const file_api_sam_proto_rawDesc = "" +
	"\n" +
	"\rapi/sam.proto\x12\x06sam.v1\"%\n" +
	"\tAuthFrame\x12\x18\n" +
	"\abiscuit\x18\x01 \x01(\fR\abiscuit\">\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd8\x01\n" +
	"\tMeshEvent\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.sam.v1.MeshEvent.TypeR\x04type\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12$\n" +
	"\x0enew_public_key\x18\x04 \x01(\fR\fnewPublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"$\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06BANNED\x10\x00\x12\x10\n" +
	"\fKEY_ROTATION\x10\x01\":\n" +
	"\rEnrollRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\"\xc5\x01\n" +
	"\x0eEnrollResponse\x12#\n" +
	"\rbiscuit_token\x18\x01 \x01(\fR\fbiscuitToken\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12$\n" +
	"\x0ehub_public_key\x18\x03 \x01(\fR\fhubPublicKey\x12#\n" +
	"\rhub_addresses\x18\x04 \x03(\tR\fhubAddresses\x12\x1e\n" +
	"\n" +
	"expiration\x18\x05 \x01(\x03R\n" +
	"expiration\"l\n" +
	"\vServiceInfo\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.sam.v1.ServiceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x95\x01\n" +
	"\x0eCommandBackend\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x121\n" +
	"\x03env\x18\x02 \x03(\v2\x1f.sam.v1.CommandBackend.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x16RegisterServiceRequest\x12-\n" +
	"\aservice\x18\x01 \x01(\v2\x13.sam.v1.ServiceInfoR\aservice\x12\x1f\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tH\x00R\ttargetUrl\x122\n" +
	"\acommand\x18\x03 \x01(\v2\x16.sam.v1.CommandBackendH\x00R\acommandB\t\n" +
	"\abackend\"\x99\x01\n" +
	"\x12DiscoveredProvider\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12&\n" +
	"\x0flocal_proxy_url\x18\x02 \x01(\tR\rlocalProxyUrl\x12\x19\n" +
	"\bsrv_name\x18\x03 \x01(\tR\asrvName\x12'\n" +
	"\x0fsrv_description\x18\x04 \x01(\tR\x0esrvDescription\"k\n" +
	"\x0fHubInfoResponse\x12\x1f\n" +
	"\voidc_issuer\x18\x01 \x01(\tR\n" +
	"oidcIssuer\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience*s\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SERVICE_TYPE_MCP\x10\x01\x12\x1a\n" +
	"\x16SERVICE_TYPE_INFERENCE\x10\x02\x12\x14\n" +
	"\x10SERVICE_TYPE_A2A\x10\x03B\x1bZ\x19github.com/google/sam/apib\x06proto3"

var (
	file_api_sam_proto_rawDescOnce sync.Once
	file_api_sam_proto_rawDescData []byte
)

func file_api_sam_proto_rawDescGZIP() []byte {
	file_api_sam_proto_rawDescOnce.Do(func() {
		file_api_sam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sam_proto_rawDesc), len(file_api_sam_proto_rawDesc)))
	})
	return file_api_sam_proto_rawDescData
}

var file_api_sam_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_sam_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_sam_proto_goTypes = []any{
	(ServiceType)(0),               // 0: sam.v1.ServiceType
	(MeshEvent_Type)(0),            // 1: sam.v1.MeshEvent.Type
	(*AuthFrame)(nil),              // 2: sam.v1.AuthFrame
	(*AuthResponse)(nil),           // 3: sam.v1.AuthResponse
	(*MeshEvent)(nil),              // 4: sam.v1.MeshEvent
	(*EnrollRequest)(nil),          // 5: sam.v1.EnrollRequest
	(*EnrollResponse)(nil),         // 6: sam.v1.EnrollResponse
	(*ServiceInfo)(nil),            // 7: sam.v1.ServiceInfo
	(*CommandBackend)(nil),         // 8: sam.v1.CommandBackend
	(*RegisterServiceRequest)(nil), // 9: sam.v1.RegisterServiceRequest
	(*DiscoveredProvider)(nil),     // 10: sam.v1.DiscoveredProvider
	(*HubInfoResponse)(nil),        // 11: sam.v1.HubInfoResponse
	nil,                            // 12: sam.v1.CommandBackend.EnvEntry
}
var file_api_sam_proto_depIdxs = []int32{
	1,  // 0: sam.v1.MeshEvent.type:type_name -> sam.v1.MeshEvent.Type
	0,  // 1: sam.v1.ServiceInfo.type:type_name -> sam.v1.ServiceType
	12, // 2: sam.v1.CommandBackend.env:type_name -> sam.v1.CommandBackend.EnvEntry
	7,  // 3: sam.v1.RegisterServiceRequest.service:type_name -> sam.v1.ServiceInfo
	8,  // 4: sam.v1.RegisterServiceRequest.command:type_name -> sam.v1.CommandBackend
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_sam_proto_init() }
func file_api_sam_proto_init() {
	if File_api_sam_proto != nil {
		return
	}
	file_api_sam_proto_msgTypes[7].OneofWrappers = []any{
		(*RegisterServiceRequest_TargetUrl)(nil),
		(*RegisterServiceRequest_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sam_proto_rawDesc), len(file_api_sam_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_sam_proto_goTypes,
		DependencyIndexes: file_api_sam_proto_depIdxs,
		EnumInfos:         file_api_sam_proto_enumTypes,
		MessageInfos:      file_api_sam_proto_msgTypes,
	}.Build()
	File_api_sam_proto = out.File
	file_api_sam_proto_goTypes = nil
	file_api_sam_proto_depIdxs = nil
}
