name: Deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths: 
      - 'site/**'
      - 'docs/**'
      - '.github/workflows/deploy-github-pages.yml'
  pull_request:
    paths:
      - 'site/**'
      - 'docs/**'
      - '.github/workflows/deploy-github-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive  # Fetch any git submodules if configured

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.136.5' # Matching local Hugo version
          extended: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      - name: Install PostCSS dependencies
        run: |
          npm init --yes
          npm install --save-dev autoprefixer postcss-cli postcss
        working-directory: ./site

      - name: Build Hugo Site
        run: hugo --baseURL https://sam-mesh.dev --minify
        working-directory: ./site

      - name: Create CNAME
        run: echo "sam-mesh.dev" > ./site/public/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/public

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
