# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Test Flutter App

on:
  push:
    branches:
      - 'main'
      - 'mmobile'
    tags:
      - 'v*'
  pull_request:
    branches: [ main, mmobile ]

env:
  GO_VERSION: "1.26"

jobs:
  build-ffi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
    - run: make mobile-ffi-host

  analyze-flutter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
    - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
      working-directory: mobile/sam-node-app
    - name: Analyze code
      run: flutter analyze
      working-directory: mobile/sam-node-app

  e2e-android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
      with:
        channel: 'stable'
    - name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run E2E Integration Test in Android Emulator
      uses: ReactiveCircus/android-emulator-runner@b86636dcd5723ef0161e7f288e9bd0ad01258791 # v2.30.0
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        script: ./mobile/mobile_e2e.sh
